### PR TITLE
Do not overwrite putFields field in accessor

### LINKED ISSUE #136: `fields` field gets overwritten for every field
https://github.com/eclipse-ee4j/orb/blob/08d26c206cba71fa52b3e15c86baa80900aded9c/orbmain/src/main/java/com/sun/corba/ee/impl/io/OutputStreamHook.java#L145-L150

Thus - if class defines few fields **AND** in its `writeObject` methods registers each one with separate `outStream.putFields().put(...)` - like `ConcurrentHashMap` (JDK8) does:
https://github.com/openjdk/jdk/blob/9a9add8825a040565051a09010b29b099c2e7d49/jdk/src/share/classes/java/util/concurrent/ConcurrentHashMap.java#L1403-L1405
then only one field is serialized with value, and the remaining are serialized as `nulls` in (example for `int`):
https://github.com/eclipse-ee4j/orb/blob/08d26c206cba71fa52b3e15c86baa80900aded9c/orbmain/src/main/java/com/sun/corba/ee/impl/io/IIOPOutputStream.java#L668-L674

### PR DESCRIPTION
**Pull request by pzygielo**
- Fixes #136

### CODE REVIEW

**Comment by smillidge** [comment]
Is there a specific issue this is fixing?

**Comment by pzygielo** [comment]
> Is there a specific issue this is fixing?

There it is
- #136

This is related to
- #131

but does not resolve it completely.

**Comment by pzygielo** [comment]
I described the issue for myself first, earlier, and it mentions `fields` field. But the change is about `putFields`. I have to re-do my finding and do correction (probably in issue).

**Comment by pzygielo** [comment]
It was about `fields` at
https://github.com/eclipse-ee4j/orb/blob/08d26c206cba71fa52b3e15c86baa80900aded9c/orbmain/src/main/java/com/sun/corba/ee/impl/io/OutputStreamHook.java#L120
being new, one-element only map, for every new field put to the stream. But due to `putFields` being overwritten.

**Comment by pzygielo** [comment]
In SE it is protected on the method level: https://github.com/openjdk/jdk8u/blob/dfa5f14848df6b4b41f839004d6baf37ca2f4f8d/corba/src/share/classes/com/sun/corba/se/impl/io/OutputStreamHook.java#L156-L162

Interesting
- this is how they protected it: https://github.com/openjdk/jdk8u/commit/a8e9ef12aee12dd87b60fd66168e21fcb4d64516
- this is why: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8068721

**Comment by pzygielo** [comment]
I believe there are two separate issues here.
I propose to solve them separately.

**Comment by pzygielo** [comment]
May I ask for review, please?

**Review by smillidge — APPROVED** [review]

**Pull request merged**
