### PR TITLE
Revert license comments on test

### PR DESCRIPTION
**Pull request by smillidge**
Reverts addition of license headers to source files used as masters to test RMIC and IDL generation

### CODE REVIEW

**Review by lukasj — APPROVED** [review]
LGTM; an update to make/copyright-information/copyright-exclude.txt will be needed should there be a will to use gf-copyright plugin going forward

**Comment by smillidge** [comment]
thanks I will add the excludes. Does it need full path as I'm not familiar with the plugin?

**Comment by lukasj** [comment]
"The excluded names are substrings (not regular expressions) that are matched against the path/file name." (see [its readme](https://github.com/eclipse-ee4j/glassfish-copyright-plugin/blob/master/README.md)), so I'd add sth like:

```
idlj/src/test/masters/
```

there; should be easy to verify by running: `mvn glassfish-copyright-plugin:{copyright,check}` locally as the configuration itself is in the root pom already

**Review by m0mus — APPROVED** [review]
LGTM

**Pull request merged**
