### PR TITLE
Merge 4.2.3 Release Branch

### PR DESCRIPTION
**Pull request by smillidge**

### CODE REVIEW

**Comment by arjantijms** [comment]
@m0mus @russgold small ping here ;) This PR has now been open for nearly two months.

**Review by russgold — APPROVED** [review]

**Review by m0mus — APPROVED** [review]
I am approving, but it's 2021 now and you need to change the copyright years. :(

**Comment by pzygielo** [comment]
> I am approving, but it's 2021 now and you need to change the copyright years. :(

Modifications were really contributed in 2020, by bot, so perhaps such change is not needed?

**Comment by m0mus** [comment]
Maybe not. I leave it up to you.

**Comment by arjantijms** [comment]
@russgold @m0mus can this be merged?

**Pull request merged**
