### PR TITLE
Jakarta EE namespace transition

### PR DESCRIPTION
**Pull request by jGauravGupta**
Signed-off-by: Gaurav Gupta <gaurav.gupta@payara.fish>

### CODE REVIEW

**Comment by smillidge** [comment]
@russgold does this want to go into master though?

**Comment by russgold** [comment]
> @russgold does this want to go into master though?

We should do whatever we're doing for the rest of the Glassfish jakarta move, presumably. Are we doing that in a branch or in master?

**Comment by smillidge** [comment]
We are doing in master and making it a new major release

**Comment by jGauravGupta** [comment]
Closing this PR as https://github.com/eclipse-ee4j/orb/pull/99 merged.

**Pull request closed without merging**
